accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

calls/urls.py
from django.urls import path
from . import views

app_name = 'calls'

urlpatterns = [
    path('printer/results/', views.search_printer, name='search_printer'),
    path('customer/results/', views.search_customer, name='search_customer'),
    path('customer/', views.customer_list, name='customer_list'),
    path('customer/create/', views.customer_create, name='customer_create'),
    path('customer/<slug>/', views.customer_detail, name='customer_detail'),
    path('printer/', views.printer_list, name='printer_list'),
    path('customer/<slug>/create/', views.printer_create, name='printer_create'),
    path('copier/', views.copier_list, name='copier_list'),
    path('copier/create/', views.copier_create, name='copier_create'),
    path('esttime/', views.esttime_list, name='esttime_list'),
    path('esttime/create/', views.esttime_create, name='esttime_create'),
    path('printer/<slug>/', views.printer_detail, name='printer_detail'),
    path('send/', views.mail_from_web, name='mail_from_web'),
    # path('expenses/', views.product_list, name='expenses'),
    path('printer/<slug>/create/', views.call_create, name='create'),
    path('', views.calls_list, name='list'),
    path('results/', views.search, name='search'),
    path('<slug>/', views.call_detail, name='detail'),
    path('<slug>/edit/', views.call_edit, name='edit'),
    path('<slug>/delete/', views.call_delete, name='delete'),
    path('export/csv/', views.export_call_csv, name='export_call_csv'),
]

serviceapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from calls import views as call_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('calls/', include('calls.urls')),
    path('', call_views.calls_list, name='home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

calls/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import timedelta, datetime
import uuid


class EstTimeChoice(models.Model):
    description = models.CharField(max_length=300)

    def __str__(self):
        return str(self.description)


class EstTimeProfile(models.Model):
    choices = models.ManyToManyField(EstTimeChoice)


class TypeOfEstTime(models.Model):
    thirty = '0h 30min'
    fortyfive = '0h 45min'
    sixty = '1h 00min'
    seventyfive = '1h 15min'
    ninety = '1h 30min'
    hundredfive = '1h 45min'
    hundredtwenty = '2h 00min'
    hundredtwentyplus = '2h +'
    TYPE_OF_ESTTIME_CHOICES = [
        (thirty, '0h 30min'),
        (fortyfive, '0h 45min'),
        (sixty, '1h 00min'),
        (seventyfive, '1h 15min'),
        (ninety, '1h 30min'),
        (hundredfive, '1h 45min'),
        (hundredtwenty, '2h 00min'),
        (hundredtwentyplus, '2h +'),
    ]
    type_of_esttime = models.CharField(
        max_length=50,
        choices=TYPE_OF_ESTTIME_CHOICES,
        default=thirty
    )

    description_of_time = models.CharField(max_length=50)

    def __str__(self):
        return str(self.description_of_time)


class Copier(models.Model):
    cop_name = models.CharField(max_length=100)

    def __str__(self):
        return self.cop_name


class CopTypeChoice(models.Model):
    description = models.CharField(max_length=300)

    def __str__(self):
        return self.description


class CopTypeProfile(models.Model):
    choices = models.ManyToManyField(CopTypeChoice)


class TypeOfDevice(models.Model):
    HIGHVOLCC = 'High Volume COLOUR copier'
    HIGHVOLMC = 'High Volume MONO copier'
    MIDVOLCC = 'Mid Volume COLOUR copier'
    MIDVOLMC = 'Mid Volume MONO copier'
    PRMON = 'Printer MONO'
    PRCOL = 'Printer COLOUR'
    MFPMON = 'Multifunction MONO'
    MFPCOL = 'Multifunction COLOUR'
    BARPR = 'Barcode Printer'
    TYPE_OF_DEVICE_CHOICES = [
        (HIGHVOLCC, 'High Volume COLOUR copier'),
        (HIGHVOLMC, 'High Volume MONO copier'),
        (MIDVOLCC, 'Mid Volume COLOUR copier'),
        (MIDVOLMC, 'Mid Volume MONO copier'),
        (PRMON, 'Printer MONO'),
        (PRCOL, 'Printer COLOUR'),
        (MFPMON, 'Multifunction MONO'),
        (MFPCOL, 'Multifunction COLOUR'),
        (BARPR, 'Barcode Printer'),
    ]
    type_of_device = models.CharField(
        max_length=50,
        choices=TYPE_OF_DEVICE_CHOICES,
        default=MIDVOLCC,
    )

    device_name = models.CharField(max_length=50)

    def __str__(self):
        return self.device_name


class Copier(models.Model):
    cop_name = models.CharField(max_length=100)

    def __str__(self):
        return self.cop_name


class Customer(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    post_code = models.CharField(max_length=10)
    note = models.TextField(max_length=1000, null=True, blank=True)
    slug = models.SlugField(unique=False)

    def __str__(self):
        return str(self.name)


class Printer(models.Model):
    name = models.CharField(max_length=100)
    ser_num = models.CharField(max_length=100)
    customer = models.ForeignKey(Customer, default=None, on_delete=models.CASCADE)
    slug = models.SlugField(unique=False)

    def __str__(self):
        return str(self.name) + ' - S/N: ' + self.ser_num


class Call(models.Model):
    printer = models.ForeignKey(Printer, default=None, on_delete=models.SET_NULL, null=True)
    page_count_b = models.IntegerField(default=0)
    page_count_c = models.IntegerField(default=0)
    error_code = models.CharField(max_length=100, null=True, blank=True)
    action = models.TextField(max_length=1000, null=True, blank=True)
    external_number = models.CharField(max_length=100, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    date_start = models.DateTimeField(auto_now_add=False, null=True, blank=True)
    date_finish = models.DateTimeField(auto_now_add=False, null=True, blank=True)
    expenses = models.FloatField(max_length=10, default=0.00)
    slug = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for call')
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    thumb = models.ImageField(upload_to='media/', default='default.png')

    def __str__(self):
        return str(self.printer.name)

    def snippet(self):
        return self.action[:50] + '...'

    def work_time(self):
        return self.date_finish - self.date_start

    def total_page(self):
        return int(self.page_count_b) + int(self.page_count_c)

    def date_end(self):
        if self.date_estimate == TypeOfEstTime.thirty:
            return self.date_start + timedelta(minutes=30, hours=0)
        elif str(self.date_estimate) == TypeOfEstTime.fortyfive:
            return self.date_start + timedelta(minutes=45, hours=0)
        elif str(self.date_estimate) == TypeOfEstTime.sixty:
            return self.date_start + timedelta(minutes=0, hours=1)
        elif str(self.date_estimate) == TypeOfEstTime.seventyfive:
            return self.date_start + timedelta(minutes=15, hours=1)
        elif str(self.date_estimate) == TypeOfEstTime.ninety:
            return self.date_start + timedelta(minutes=30, hours=1)
        elif str(self.date_estimate) == TypeOfEstTime.hundredfive:
            return self.date_start + timedelta(minutes=45, hours=1)
        elif str(self.date_estimate) == TypeOfEstTime.hundredtwenty:
            return self.date_start + timedelta(minutes=0, hours=2)
        elif str(self.date_estimate) == TypeOfEstTime.hundredtwentyplus:
            return self.date_start + timedelta(minutes=30, hours=2)
        else:
            return str("Incorrect date format")

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Calls list</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!--    <link rel="stylesheet" href="{% static 'styles.css' %}">-->
    <link rel="stylesheet" href="{% static 'main/gijgo.min.css' %}">
</head>
<body>
<div class="container">
    <nav class="navbar navbar-dark bg-dark">

            {% if user.is_authenticated %}

    <a class="navbar-brand btn btn-success my-2 my-sm-0" href="{% url 'home' %}" class="highlight">HOME / CALLS</a>
    <a class="navbar-brand btn btn-success my-2 my-sm-0" href="{% url 'calls:customer_list' %}">CUSTOMERS</a>
    <a class="navbar-brand btn btn-success my-2 my-sm-0" href="{% url 'calls:printer_list' %}">PRINTERS</a>
    <a class="navbar-brand btn btn-success my-2 my-sm-0" href="{% url 'calls:export_call_csv' %}">EXPENSES</a>

    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
        {% csrf_token %}
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Logout [{{ user }}]</button>
    </form>

            {% else %}
            <a  class="navbar-brand" href="{% url 'accounts:login' %}" class="highlight">Log in</a>
            <a  class="navbar-brand" href="{% url 'accounts:signup' %}" class="highlight">Not registered? -> Sign up</a>
            {% endif %}

    </nav>
    {% block content %}
    {% endblock %}
</div>
<script src="{% static 'main/jquery.min.js' %}"></script>
<script src="{% static 'main/gijgo.min.js' %}" type="text/javascript"></script>
<script type="text/javascript">
    $('#id_date_start').datetimepicker({ footer: true, modal: true, format: 'yyyy-mm-dd HH:MM', width: 300 });
    $('#id_date_finish').datetimepicker({ footer: true, modal: true, format: 'yyyy-mm-dd HH:MM', width: 300 });

</script>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test home</title>
</head>
<body>
Home template - test
</body>
</html>