calls/urls.py
from django.urls import path
from . import views

app_name = 'calls'

urlpatterns = [
    path('printer/results/', views.search_printer, name='search_printer'),
    path('customer/results/', views.search_customer, name='search_customer'),
    path('customer/', views.customer_list, name='customer_list'),
    path('customer/create/', views.customer_create, name='customer_create'),
    path('customer/<slug>/', views.customer_detail, name='customer_detail'),
    path('printer/', views.printer_list, name='printer_list'),
    path('customer/<slug>/create/', views.printer_create, name='printer_create'),
    path('copier/', views.copier_list, name='copier_list'),
    path('copier/create/', views.copier_create, name='copier_create'),
    path('esttime/', views.esttime_list, name='esttime_list'),
    path('esttime/create/', views.esttime_create, name='esttime_create'),
    path('printer/<slug>/', views.printer_detail, name='printer_detail'),
    path('send/', views.mail_from_web, name='mail_from_web'),
    # path('expenses/', views.product_list, name='expenses'),
    path('printer/<slug>/create/', views.call_create, name='create'),
    path('', views.calls_list, name='list'),
    path('results/', views.search, name='search'),
    path('<slug>/', views.call_detail, name='detail'),
    path('<slug>/edit/', views.call_edit, name='edit'),
    path('<slug>/delete/', views.call_delete, name='delete'),
    path('export/csv/', views.export_call_csv, name='export_call_csv'),
]

calls/templates/calls/call_create.html
{% extends 'base_layout.html' %}
{% block content %}
<h3 class="h3 font-weight-normal">Create new call</h3>
<br>
 <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="" value="{{ call }}">
                        {% include 'calls/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form><br>
<script src="/static/slugify.js"></script>
{% endblock %}

calls/templates/calls/call_delete.html
{% extends 'base_layout.html' %}
{% block content %}
<h3 class="h3 font-weight-normal">Delete call</h3>
<form class="site-form" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <p class="p_delete">Do you want to delete a call for:</p> <p>{{ call.printer }}</p>
    <input class="btn btn-danger my-2 my-sm-0" type="submit" value="YES! Delete">
</form><br>
<a href="{% url 'calls:detail' slug=call.slug %}"><button class="btn btn-success my-2 my-sm-0" type="submit">NO!, return to the call</button></a>
{% endblock %}

calls/templates/calls/call_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<h3 class="h3 font-weight-normal">Call detail</h3>

<div>
    {% if user.is_authenticated %}
    <p class="text-right"><a href="{% url 'calls:edit' slug=call.slug %}" class="btn btn-success my-2 my-sm-0">Edit call</a> </p>
    {% endif %}
</div>
<table class="table table-bordered">
  <thead class="thead-dark">
    <tr class="bg-dark">
      <td class="text-white" colspan="3">

{% for printer in printers %}
    {% if call.printer == printer %}
       {{ printer.customer }}
    {% endif %}
{% endfor %}

      </td>
        <td class="text-white">
            Call ext. number: {{ call.external_number }}
        </td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><b>Model - serial number:</b></th>
      <td colspan="3">{{ call.printer }}</td>

    </tr>
    <tr>
      <th scope="row"><b>Meter readings:</b></th>
      <td>Black: {{ call.page_count_b }} </td>
      <td>Colour: {{ call.page_count_c }} </td>
        <td><b>Total:</b> {{ call.total_page }} </td>
    </tr>
    <tr>
      <th scope="row"><b>Error code or reason of visit:</b></th>
      <td colspan="3">
              {% if call.error_code == 'RTF' %}
        <span class="badge badge-success">{{ call.error_code }}</span>
    {% elif call.error_code == 'Installation' or call.error_code == 'ECC' %}
        <span class="badge badge-primary">{{ call.error_code }}</span>
    {% elif call.error_code != 'Installation' or  call.error_code != 'RTF' or call.error_code != 'ECC' %}
        <span class="badge badge-danger">{{ call.error_code }}</span>
    {% endif %}

<span class="text-right"><b> Estimate work time:</b> {{ call.date_estimate }}</span>
      </td>
    </tr>

      <tr>

      <td scope="row" colspan="4"><b>Solution and needed parts:</b></td>

    </tr>
      <tr>

      <td scope="row" colspan="4">{{ call.action|linebreaksbr }}</td>

    </tr>
        <tr>

            <td scope="row" colspan="4"><b>Summary:</b></td>
    </tr>
      <tr>
      <th scope="row">Date / Time:</th>
          <td><b>Arrival:</b> {{ call.date_start | date:'Y-m-d' }} / {{ call.date_start | time:'H:i' }} </td>
          <td><b>Finish:</b> {{ call.date_finish | date:'Y-m-d' }} / {{ call.date_finish | time:'H:i' }} </td>
        <td><b>Work time:</b> {{ call.work_time }} </td>
    </tr>

          <tr>
      <th scope="row">Engineer:</th>
          <td>{{ call.author }}</td>
          <td><b>Car park costs:</b></td>
        <td> &pound; {{ call.expenses }}</td>
    </tr>

      <tr>

      <td scope="row" colspan="4"><b>Helpful picture:</b></td>

    </tr>

        <tr>

      <td scope="row" colspan="4">

              <div class="media">
    <img class="img-fluid rounded mx-auto d-block" src="{{ call.thumb.url }}"/>
    </div>
      </td>

    </tr>

  </tbody>
</table>


<div>

    {% if user.is_authenticated %}
    <p class="text-right"><a href="{% url 'calls:delete' slug=call.slug %}" class="btn-sm btn-success my-2 my-sm-0">Delete call</a> </p>
    {% endif %}
</div>

{% endblock %}

calls/templates/calls/call_edit.html
{% extends 'base_layout.html' %}
{% block content %}

<h3 class="h3 font-weight-normal">Call EDIT</h3>
<br>
 <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="" value="{{ call }}">
                        {% include 'calls/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form><br>
<script src="/static/slugify.js"></script>
{% endblock %}

calls/templates/calls/calls_list.html
{% extends 'base_layout.html' %}
{% block content %}
<nav class="navbar navbar-dark bg-dark justify-content-center">
    <form class="form-inline my-2 my-lg-0 col-xs-4" method="get" action="{% url 'calls:search' %}">
    <input class="form-control mr-sm-2 col-xs-4" name="q" placeholder="search error code..." value="{{ request.GET.q }}">
    <button class="btn btn-success my-2 my-sm-0" data-toggle="collapse"  type="submit">Search</button>
    </form>
</nav>
<!--<h3 class="h3 font-weight-normal">List of service calls</h3>-->
<table class="table table-hover">
<thead>
<tr>
<th scope="col">Times:</th>
<th scope="col">List of calls</th>
</tr>
</thead>
{% for call in calls %}
    {% for printer in printers %}
        {% if call.printer == printer %}
            <tbody>
                <tr>
                    <td>
                        <p class="h6">
                            <p class="font-weight-bold">{{ call.date_start|date:'l j M Y' }}</p>

                        <b>Estimate time:</b> {{ call.date_estimate }}<br>
                            Real time:<br>
                            <b>Start:</b> {{ call.date_start | time:'H:i'  }} <br>
                            <b>Finish:</b> {{ call.date_finish | time:'H:i'  }}<br>
                        </p>
                    </td>
                    <td>
                        <a href="{% url 'calls:detail' slug=call.slug %}">
                            <h2 class="h3 mb-3 font-weight-normal">
                            {{ call.printer }}
                            {% if call.error_code == 'RTF' %}
                            <span class="badge badge-success float-right">{{ call.error_code }}</span>
                            {% elif call.error_code == 'Installation' or call.error_code == 'ECC' %}
                            <span class="badge badge-primary float-right">{{ call.error_code }}</span>
                            {% elif call.error_code != 'Installation' or  call.error_code != 'RTF' or call.error_code != 'ECC' %}
                            <span class="badge badge-danger float-right">{{ call.error_code }}</span>
                            {% endif %}
                            </h2>
                        </a>
                    </td>
                </tr>
            </tbody>
        {% endif %}
    {% endfor %}
{% endfor %}
</table>
<ul class="pagination pagination-lg justify-content-center">
    {% if calls.has_previous %}
    <li class="page-item"><a class="page-link" href="?page=1">&laquo; first &laquo;</a></li>
    <li class="page-item">
        <a class="page-link" href="?page={{ calls.previous_page_number }}" tabindex="-1">Previous</a>
    </li>
    {% endif %}
    <li class="page-item">
        <a class="page-link">Page {{ calls.number }} of {{ calls.paginator.num_pages }}</a>
    </li>
    {% if calls.has_next %}
    <li class="page-item">
    <a class="page-link" href="?page={{ calls.next_page_number }}">Next</a>
    </li>
    <li class="page-item"><a class="page-link" href="?page={{ calls.paginator.num_pages }}">&raquo; last &raquo;</a></li>
    {% endif %}
</ul>
{% endblock %}

calls/templates/calls/customer_create.html
{% extends 'base_layout.html' %}
{% block content %}
<h3 class="h3 font-weight-normal">Create new customer</h3>
<br>
<form class="form-horizontal" action="{% url 'calls:customer_create' %}" method="post" enctype="multipart/form-data">
    <div class="form-group">
        {% csrf_token %}
    <label class="control-label col-sm-2">Name</label>
        {{ form.name }}</div>
    <div class="form-group">
    <label class="control-label col-sm-2">Address</label>
        {{ form.address }}</div>
    <div class="form-group">
    <label class="control-label col-sm-2">Post code</label>
        {{ form.post_code }}</div>
    <div class="form-group">
    <label class="control-label col-sm-2">Note</label>
        {{ form.note }}</div>
    <div class="form-group">
    <label class="control-label col-sm-2">Slug</label>
        {{ form.slug }}</div>
    <input class="btn btn-success my-2 my-sm-0" type="submit" value="Create">
</form>

<script src="/static/slugify_cust.js"></script>
{% endblock %}

calls/templates/calls/customer_detail.html
{% extends 'base_layout.html' %}
{% block content %}
<br>
<h3 class="h3 font-weight-normal">Customer detail</h3>
<p><b>Name:</b> {{ customer.name }}</p>
<p><b>Address:</b> {{ customer.address }}</p>
<p><b>Post code:</b> {{ customer.post_code }}</p>
<p><b>Note:</b> {{ customer.note|linebreaksbr }}</p>
<table class="table table-hover">
    <thead>
        <tr>
        <th scope="col">List of printers / photocopiers: <a href="{% url 'calls:printer_create' customer.slug %}" class="btn btn-success my-2 my-sm-0">Add new printer</a></th>
        </tr>
    </thead>
    <tbody>
        {% for printer in printers %}
        {% if printer.customer == customer %}
        <tr>
        <td>
            <a href="{% url 'calls:printer_detail' slug=printer.slug %}">
            {{ printer }}
            </a>
        </td>
        </tr>
        {% endif %}{% endfor %}
    </tbody>
</table>
{% endblock %}

calls/templates/calls/customer_list.html
{% extends 'base_layout.html' %}
{% block content %}
<nav class="navbar navbar-dark bg-dark justify-content-center">
    <form class="form-inline my-2 my-lg-0 col-xs-4" method="get" action="{% url 'calls:search_customer' %}">
    <input class="form-control mr-sm-2 col-xs-4" name="q" placeholder="search customer..." value="{{ request.GET.q }}">
    <button class="btn btn-success my-2 my-sm-0" data-toggle="collapse"  type="submit">Search</button>
    </form>
</nav>
<h3 class="h3 font-weight-normal">Customers list</h3>
<p>
<a href="{% url 'calls:customer_create' %}" class="btn btn-success my-2 my-sm-0">Add new customer</a>
</p>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Customer name:</th>
    </tr>
  </thead>

  <tbody>{% for customer in customers %}
    <tr>
      <td><a class="h4" href="{% url 'calls:customer_detail' slug=customer.slug %}">{{ customer.name }}</a>
</td>

            </tr>{% endfor %}
  </tbody>
</table>

<ul class="pagination pagination-lg justify-content-center">
    {% if customers.has_previous %}
    <li class="page-item"><a class="page-link" href="?page=1">&laquo; first &laquo;</a></li>
    <li class="page-item">
        <a class="page-link" href="?page={{ customers.previous_page_number }}" tabindex="-1">Previous</a>
    </li>
    {% endif %}
    <li class="page-item">
        <a class="page-link">Page {{ customers.number }} of {{ customers.paginator.num_pages }}</a>
    </li>
    {% if customers.has_next %}
    <li class="page-item">
    <a class="page-link" href="?page={{ customers.next_page_number }}">Next</a>
    </li>
    <li class="page-item"><a class="page-link" href="?page={{ customers.paginator.num_pages }}">&raquo; last &raquo;</a></li>
    {% endif %}
</ul>
{% endblock %}

calls/templates/calls/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

calls/templates/calls/mail_sent.html
{% extends 'base_layout.html' %}
{% block content %}

    <h2>Email has been sent!</h2>
<div>Check your Inbox</div>


{% endblock %}

calls/templates/calls/printer_create.html
{% extends 'base_layout.html' %}
{% block content %}
<h3 class="h3 font-weight-normal">Create new printer</h3>
<br>
 <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="album" value="{{ printer_create }}">
                        {% include 'calls/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form><br>
<script src="/static/slugify_printer.js"></script>
{% endblock %}

calls/templates/calls/printer_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<h3 class="h3 font-weight-normal">Printer detail</h3>
<p class="text-white bg-dark my-sm-3">Customer: {{ printer.customer }}</p>
<p><b>Model:</b> {{ printer.name }}<br><b>Serial number:</b> {{ printer.ser_num }}</p>
<a href="{% url 'calls:create' printer.slug %}" class="btn btn-success my-2 my-sm-0">Add new CALL</a>
<p class="font-weight-bold">Service history:</p>
<hr class="text-dark" style="width: 100%; border-top: 3px dashed;">

{% for call in calls %}

    {% if call.printer == printer %}

<a href="{% url 'calls:detail' slug=call.slug %}"> FULL DETAILS OF CALL</a>

<p><b>Engineer:</b> {{ call.author }}<br>
    <b>Arrival:</b> {{ call.date_start | date:'Y-m-d' }} / {{ call.date_start | time:'H:i' }}<br>
        <b>Finish:</b> {{ call.date_finish | date:'Y-m-d' }} / {{ call.date_finish | time:'H:i' }}<br>
        <b>Work time:</b> {{ call.work_time }}</p>
<p><b>Meter reading:</b> Black {{ call.page_count_b }} Colour: {{ call.page_count_c }}</p>

<p><b>External call number:</b> {{ call.external_number }}</p>
<p><b>Error code:</b>
    {% if call.error_code == 'RTF' %}
        <span class="badge badge-success">{{ call.error_code }}</span>
    {% elif call.error_code == 'Installation' or call.error_code == 'ECC' %}
        <span class="badge badge-primary">{{ call.error_code }}</span>
    {% elif call.error_code != 'Installation' or  call.error_code != 'RTF' or call.error_code != 'ECC' %}
        <span class="badge badge-danger">{{ call.error_code }}</span>
    {% endif %}
</p>
<p><b>Action:</b> {{ call.action|linebreaksbr }}</p>
<hr class="text-dark" style="width: 100%; border-top: 3px dashed;">
    {% endif %}

{% endfor %}



{% endblock %}

calls/templates/calls/printer_list.html
{% extends 'base_layout.html' %}
{% block content %}

<nav class="navbar navbar-dark bg-dark justify-content-center">
    <form class="form-inline my-2 my-lg-0 col-xs-4" method="get" action="{% url 'calls:search_printer' %}">
    <input class="form-control mr-sm-2 col-xs-4" name="q" placeholder="search printer..." value="{{ request.GET.q }}">
    <button class="btn btn-success my-2 my-sm-0" data-toggle="collapse"  type="submit">Search</button>
    </form>
</nav>
<h3 class="h3 font-weight-normal">Printers list</h3>
<p>

</p>
<table class="table table-hover">
    <thead>
        <tr>
        <th scope="col">Printer:</th>
        </tr>
    </thead>
    <tbody>{% for printer in printers %}
        <tr>
            <td>
            <a href="{% url 'calls:printer_detail' slug=printer.slug %}">
            <span class="text-dark">   {{ printer.name }} [s/n: {{ printer.ser_num }} ]</span><br>
            {{ printer.customer }}
            </a>
            </td>
        </tr>{% endfor %}
    </tbody>
</table>
<ul class="pagination pagination-lg justify-content-center">
    {% if printers.has_previous %}
    <li class="page-item"><a class="page-link" href="?page=1">&laquo; first &laquo;</a></li>
    <li class="page-item">
        <a class="page-link" href="?page={{ printers.previous_page_number }}" tabindex="-1">Previous</a>
    </li>
    {% endif %}
    <li class="page-item">
        <a class="page-link">Page {{ printers.number }} of {{ printers.paginator.num_pages }}</a>
    </li>
    {% if printers.has_next %}
    <li class="page-item">
    <a class="page-link" href="?page={{ printers.next_page_number }}">Next</a>
    </li>
    <li class="page-item"><a class="page-link" href="?page={{ printers.paginator.num_pages }}">&raquo; last &raquo;</a></li>
    {% endif %}
</ul>
{% endblock %}